### ISSUE TITLE
Documentation on how to use?

### ISSUE THREAD

**Issue by pfortin-urbn** [aerogo/nano#6]
Where can I find docs and example usages?  This is a valid question for all aero projects and sub-projects.  I'd love to give it a spin but I can't find any complete examples and docs

**Comment by akyoto** [comment]
Thank you for the interest in the project!

Regarding the nano database: The project has not been finalized yet, a user-friendly documentation is currently missing on purpose.

If you feel experimental and want to contribute to bug fixes, please take a look at the [tests](https://github.com/aerogo/nano/blob/master/Namespace_test.go#L12). The [API surface](https://godoc.org/github.com/aerogo/nano) is very small and the usage can be seen in the test files.

I do not give any stability guarantees for the current version.

Could you let me know if you plan on a) contributing or b) only using it in production as an end-user? Then I can give a more detailed reply for your needs.

**Comment by p4tin** [comment]
I had no current plans to use it in production but I will give it a try and see how it could be used in a aero / api environment because I find it intriguing.

**Comment by ghost** [comment]
I had the same question.

Nano sounds interesting but I'm not going to read through source in order to figure out how to even try it.

I think you're making a mistake by omitting it.  I've now got nano filed in my brain as "intentionally unusable" and will probably never circle back to it.

**Comment by akyoto** [comment]
@uselessdetails

> I think you're making a mistake by omitting it. I've now got nano filed in my brain as "intentionally unusable"

You seem to assume all sorts of "evil" behind a decision.

Let me explain:

> The project has not been finalized yet, a user-friendly documentation is currently missing on purpose.

Yes, there is no documentation, because I don't want people to start using a version that has a bug and isn't complete yet.
One bug related to inter-process communication still remains to this date.

You might ask: Why is this bug not fixed?
The reasons are:

1. I currently don't have a lot of free time and resources to dedicate to open source.
2. There was a complete rewrite planned with a much better architecture using a different protocol.

Until I find the time and finances to fix the problems in the current version, please do not use this library.
It will remain on GitHub because a few of my old Go projects depend on this module in its current state.
